Add a 'static_tags' option to disable automatic merging of tags
cloudposse/terraform-null-label pull request #131
Opened 2021-08-09 19:55 UTC by Makeshift

## what
* Adds a new variable `static_tags`, set to false by default, which stops the module from merging in new tags and instead uses the `tags` variable in the input as-is, including handing it off to other modules as necessary

## why
* Helps avoid https://github.com/hashicorp/terraform-provider-aws/issues/18311
* Being able to precompute labels which are then passed into `cloudposse` modules can be useful in certain circumstances

I have a fork of `terraform-null-label` that removes tags that interfere with provider `default_tags`, but this isn't obeyed by downstream cloudposse modules. This PR should make it possible to pass context in and force null_label to not make any tags, or only make a subset of the tags :)

## references
* https://github.com/hashicorp/terraform-provider-aws/issues/18311

2021-08-09 19:55 UTC, Makeshift commented
/test all

2021-08-11 23:15 UTC, nitrocode commented
/test all

2021-08-13 20:24 UTC, Nuru requested changes
@Makeshift Thank you for this contribution.

I think I understand the problem, though maybe you want to explain it in further details, because it does not look to me like this solves the problem.

As I understand it, the issue is that the current AWS provider does not like it when a resource's tags have the same keys as the provider's `default_tags`. However, in some cases, modules add tags that are critical to proper functioning of the module, such as tagging resources as managed by an autoscaler or belonging to a Kubernetes cluster. So we cannot allow an option that blocks modules from adding tags.

To me this suggest 2 reasonable solutions:

1. Tell people not to use the `default_tags` option to the provider and instead implement `default_tags` in null-label and have people use null-label's `tags` output. This has the added advantage of properly allowing tags to be overridden, which the AWS provider seem not to support. Of course the disadvantage is that this does not cover any resources created by modules that do not use null-label.
2. Add some input like `suppress_tags` which provides a list of tag keys to filter out of the `tags` output, so those tags are not set in resources. The trade-off here is that while this ensures all resources get the default tags via the provider, the default tags cannot be overridden. 

@Makeshift What do you think of those solutions?

2021-08-18 18:04 UTC, Makeshift commented
You're correct in your assessment - Thank you for pointing out the flaw in disabling tags, it didn't occur to me that they could be integral to the working of certain resources/services. Do you have an example of a module that does this so I can make sure that any changes I make doesn't break it?

> 1. Tell people not to use the `default_tags` option to the provider and instead implement `default_tags` in null-label and have people use null-label's `tags` output. This has the added advantage of properly allowing tags to be overridden, which the AWS provider seem not to support. Of course the disadvantage is that this does not cover any resources created by modules that do not use null-label. And in fact, we do not even need a new input for this. Simply setting the current `tags` input with the set of default tags in a base null-label module in the root module would do it.

That disadvantage is rather a large one, unfortunately, I believe that `default_tags` is simply too convenient of an option to ignore, even if it's a little broken currently. Being able to generate tags for an entire stack without manually setting them is invaluable for costcentering.

> 2. Add some input like `suppress_tags` which provides a list of tag keys to filter out of the `tags` output, so those tags are not set in resources. The trade-off here is that while this ensures all resources get the default tags via the provider, the default tags cannot be overridden.

This seems like a reasonable compromise. You're suggesting something along the lines of allowing the user to set `suppress_tags = ["environment", "stage", "name"]`, then `tags` becomes:

```
tags = { for k, v in merge(local.generated_tags, local.input.tags): k => v if ! contains([for i in local.suppress_tags: lower(i)], lower(k)) }
```
?
@Nuru

2021-08-19 18:11 UTC, Makeshift commented
/test all

2021-08-19 20:25 UTC, Nuru commented
@Makeshift I hope you do not mind, I am going to steal this idea and some of this code and re-implement it in my current PR, rather than ask you to make additional changes.

2021-08-20 18:46 UTC, closed without merging